KhronosGroup/glTF-Project-Explorer

yarn.lock
Updating our yarn.lock file and to depend on `eslint-utils` 1.4.2 to mitigate the security issue flagged with 1.4.0.
=> Upgraded react-scripts to mitigate eslint-utils vulnerability.

public/data/glTF-projects-data.json
Updating Adobe Dimension information for version 3.0. Export glTF/GLB is now available under the File->Export menu.
=> Update glTF-projects-data.json for Adobe Dimension

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/29
=> Fixed escaped HTML for model-viewer

src/components/ProjectCard.css
Fixes #35.
Chrome doesn't do Grid Height calculations correctly. Luckily, this was pretty easy to fix as it continues to format everything correctly without the `grid-template-rows` properties.
=> Removed usages of grid-template-rows to avoid a Chrome layout bug.

package.json, yarn.lock
Three packages used by react-scripts during the build have identified vulnerabilities. While these are only used during the build process, we should still update.
=> Update react-scripts to update vulnerable packages

public/data/glTF-projects-data.json
Details about the changes will be added as a comment
in https://github.com/KhronosGroup/glTF-Project-Explorer/issues/37
=> First update pass for project list migration

public/data/glTF-projects-data.json
- Updated Verge3D links according to PR https://github.com/KhronosGroup/glTF/pull/1791
- Updated description for OSG.JS (it was called "OSK" in the title - a typo, probably) (Related: https://github.com/KhronosGroup/glTF/issues/1795 )
- Removed some closing `)`'s after several links. In most cases, hey didn't harm, but e.g. in "https://github.com/xml3d/xml3d-gltf-plugin)" it lead to a 404... 
- For UX3D, changed link to lead to the main page
- For Archilogic, changed link to lead to the main page, although they don't seem to mention glTF anywhere on their site any more...
- (A broken link for GLBoost was already fixed with the previous update, but not yet live)
=> Updated Verge3D info. Fixed broken links.

.travis.yml
Apparently, following the suggestion to use `token` instead of `github_token` breaks things.
This issue appears to be related; moving to v2 which is in beta may fix things but I don't want to do that yet: https://github.com/travis-ci/dpl/issues/1158
=> Fixing the deployment again

public/data/glTF-projects-data.json
Recently, glTF 2.0 support has been incorporated into the core [PlayCanvas engine](https://github.com/playcanvas/engine). This renders the [playcanvas-gltf](https://github.com/playcanvas/playcanvas-gltf) repo redundant.
There is also a new, open source, online [glTF viewer](https://playcanvas.com/viewer) powered by PlayCanvas. This PR adds it to the list.
=> Remove deprecated PlayCanvas lib and add new viewer

src/App.tsx, src/services/DataService.ts, yarn.lock
Something happened recently with CRA that has caused relative pathing for files in the `public` folder to fail to resolve. This PR changes our usages to use the `PUBLIC_URL` environment variable during the build to create absolute paths.
=> Fixing public relative paths

public/data/glTF-projects-data.json
An update for the glTF-related projects from Cesium.
TBD:
- Review the descriptions. E.g. Cesium for Unreal is not "directly" using glTF. Is the wording of *"3D Tiles ... based on glTF"* OK?
- Should links go to the website or GitHub? Right now, they go to the website for the "top-level" projects, but to GitHub for the "library" projects
- There was an entry for "Cesium glTF loader" that linked to https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Model.js - I assume that this will be obsolete with the link to CesiumJS, so removed it.
- OK to mention Typescript in CesiumJS? I think so, because there now is a TypeScript definitions file
- There is an entry for https://github.com/virtualgis/gltfviewer , which is not managed by Cesium, but it is based on an old version of CesiumJS - …
=> Updated Cesium projects

package.json, src/App.test.tsx, src/components/FilterBar.tsx, src/components/ProjectList.tsx, src/components/SearchBar.tsx, src/interfaces/IFilter.ts, src/store/Reducers.ts, src/store/filters/Actions.ts, src/store/filters/Reducers.ts, src/store/filters/Sagas.ts, src/store/projects/Actions.ts, src/store/projects/Reducers.ts, src/store/results/Actions.ts, src/store/results/Reducers.ts, src/store/results/Sagas.ts, tsconfig.json, yarn.lock
Tested this out locally using both `yarn start` and `yarn build`, so the resolutions _shouldn't_ break anything. There were also some changes to the defaults for ESLint that required some code style updates, and those are included here.
=> Updated packages and added some resolutions to close some security issues.

public/data/glTF-projects-data.json
An update of the projects based on the following issues:
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/84 "New Project: Zea Engine"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/87  "New Project: Unreal Engine", and adds https://www.unrealengine.com/marketplace/en-US/product/gltf-exporter
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/89 "New Project: vk_raytrace"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/91 "New project: NVIDIA Omniverse View"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/90 "Blackthread.io has been taken down", removed (without replacement for now), as per request in the issue
=> Update projects 2021 05 05

public/data/glTF-projects-data.json
Hesitated whether to use https://github.com/ZeaInc/gltf-loader or https://docs.zea.live/gltf-loader/ , and eventually used... `example.com` - \*blushes\* this fixes the link with the one to the GitHub repo
=> Fixed Zea Engine link

public/data/glTF-projects-data.json
An update of the projects based on the following issues:
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/86 : "New Project: Facebook Spark AR Studio"
- Might fix https://github.com/KhronosGroup/glTF-Project-Explorer/issues/93 : "New Project: Microsoft FlightSim"
For the Flight Simulator-related projects:
Maybe @elpie89 wants to see whether the wording is appropriate. I didn't dive too deeply into the technicalities of these projects. E.g. there does not seem to be a GitHub repo for the "Blender2MSFS" one (yet?). 
@pjcozzi You suggested adding *"FlightSim runtime itself"* in issue 93. I can see the reasoning. It may be one of the largest and most broadly visible applications of glTF until now. But it's a slippery slope: When the use of glTF becomes broader (in …
=> Update projects 2021 05 13

public/data/glTF-projects-data.json
Introducing virtual try-on for rings, bracelets, and watches.
Benefit from the state-of-the-art, real-time rendering of fine jewelry combining with the cutting-edge AR technology.
https://tryon.technology/
=> New Project: Virtual Try-On

public/data/glTF-projects-data.json
I wasn't happy that glTFast does not show up when searching for `Unity`, so I added it to the title. I hope that's fine.
=> glTFast updates

public/data/glTF-projects-data.json
I found a duplicate entry of FBX for Unreal Datasmith. This isn't really ideal for the search stuff I'm working on, so I'm fixing it. I have played around with the idea of how we can add a guard, but adding a filter for unique items adds another loop to the process that _every_ card has to go through and since this seems to be the only case of this we've ever gotten, I'm not keen to do so at this time. It's easy to fix the data and could have performance impacts if we try to add the guard.
=> Fixed duplicate FBX entry for Unreal Datasmith

README.md, public/data/glTF-projects-data.json
- Cleaned up the entries that had things like `"viewer, embeddable, self-hosted"` as their `type` to use these words as individual strings
- Updated the live-link in the README to use HTTP**S**
- During that: noticed that many entries use HTTP instead of HTTPS
- Changed all the links to use HTTPS by default
- Noticed that some of these entries are actually dead links
- Wrote a tool that reads the projects data JSON and tries to contact all links, to see whether they are 404
- Noticed that I'm in a rabbit hole...
- Ignored that...
- Fixed several links and descriptions that caused 404's or have otherwise been outdated...
I guess somebody _has_ to do something like this, occasionally. It still raises the question about how such "maintenance" can be done for larger project databases. E.g. …
=> Project data cleanup 2022 07 23

public/data/glTF-projects-data.json
I also noticed that the "import" and "load" tasks seem to have the same meaning, is that known?
=> Add fastgltf

src/components/ProjectCard.tsx, src/interfaces/IAppState.ts, src/interfaces/IProjectInfo.ts, src/store/filters/Interfaces.ts
As mentioned in https://github.com/KhronosGroup/glTF-Project-Explorer/issues/151#issuecomment-1267485047 : The `ProjectCart.tsx` that displays the actual UI element for each project still used the hard-wired `task/type/inputs...` properties of the `IProjectInfo`. This has been changed to use the general properties that are defined via `ProjectProperties` now.
=> Use ProjectProperties in ProjectCard

.travis.yml
Trying to fix the travis build, which was recently failing with
`node: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by node)`
Some guesses here: 
It probably tries to install the latest (LTS?) version of node, which is now 18, and which needs GLIBC with a version that is _higher_ than the one that is currently installed with the `xenial` distribution. According to https://docs.travis-ci.com/user/reference/xenial/#javascript-and-nodejs-support , the latest supported Node version in xenial is 12. So I'm giving that a try...
=> Fix build issues related to Node and GLIBC versions

public/data/glTF-projects-data.json
Adding details for a MATLAB class to export 3D graphs and other content from MATLAB to GLTF.
=> Adding MATLAB-GLTF to glTF-projects-data.json

.github/workflows/ci.yaml
Referring to https://github.com/KhronosGroup/glTF-Project-Explorer/issues/161#issuecomment-1470758958 , I think the condition for the deployment to be run was wrong:
```
if: ${{ github.ref == 'refs/head/main' }}    // OLD
if: ${{ github.ref == 'refs/heads/main' }}   // NEW
```
@weegeekps If that looks about right, feel free to merge.
=> Fix ref that triggers depolyoment

public/data/glTF-projects-data.json
Adding the govie-editor platform to the gltf project explorer
Govie Editor is highly leveraging the GLTF 2.0 format. Converting various asset formats to glb and using it within the viewer (based on ThreeJS).
=> govie-editor specs added

public/data/glTF-projects-data.json
- mention MaterialX support in description (glTF PBR)
- add library type because guc provides a C API
- add plugin type because guc provides a USD Sdf plugin
=> Update entry for guc
