package.json, src/store/results/Sagas.ts, yarn.lock
As per issue #1, I improved the filtering logic using the method proposed there. It now ANDs across dimensions and ORs within the dimensions.
=> Improved filtering logic.

package.json, yarn.lock
Work to prepare for initial deployment.
=> Prep for deployment

README.md
This addresses https://github.com/KhronosGroup/glTF-Project-Explorer/issues/14
Preview at https://github.com/javagl/glTF-Project-Explorer#contributions 
Comments or suggestions?
=> Extended README with contribution information

public/data/glTF-projects-data.json
- Split inputs/outputs strings that contained multiple file extensions as ONE string
- Fixed broken links for formats that had been behind "Multiple"
- Replaced some "Multiple" entries with lists of file extensions
=> First formats curation pass

src/store/results/Sagas.ts
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/20
=> Made title search case insensitive

package.json, public/data/glTF-projects-data.json, src/components/FilterBar.css, src/components/FilterBar.tsx, src/interfaces/IAppState.ts, src/interfaces/IFilter.ts, src/interfaces/IProjectInfo.ts, src/store/filters/Actions.ts, src/store/filters/Interfaces.ts, src/store/filters/Reducers.ts, src/store/filters/Sagas.ts, src/store/results/Sagas.ts, src/utils/FilterHelpers.ts
=> Implemented "Tags" and sorting of results.

public/data/glTF-projects-data.json
Update based on https://github.com/KhronosGroup/glTF-Project-Explorer/pull/27
=> Added details about SharpGLTF

public/data/glTF-projects-data.json
Added Datakit CrossManager and CrossCad/Ware SDK in the list
=> Added Datakit CrossManager and CrossCad/Ware SDK

public/data/glTF-projects-data.json
Resolved conflict from https://github.com/KhronosGroup/glTF-Project-Explorer/pull/33
=> Adding forge-convert-utils record

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/31
=> Updated entry for COMSOL

public/data/glTF-projects-data.json
=> Update DEM Net to reflect recent update

.travis.yml
I misunderstood what the `do` field is meant for, and had the wrong branch in it. Deployment will work now with this change.
=> Fixing the deploy step

.travis.yml, README.md
I also fixed some validation warnings and infos fired by the build validator.
=> Added Travis CI Build Badge to README

README.md
I added the wrong build badge before.
=> Updating the build badge in the README to be the travis-ci.com one

public/data/glTF-projects-data.json
Fixed merge conflicts and formatting errors,
replacing the original PR 56
=> Updated projects data with ProTech projects

public/data/glTF-projects-data.json
Added ProtoTech as the keyword in Product Name.
=> Updated JSON file

public/data/glTF-projects-data.json
https://github.com/drydart/model_viewer.dart
=> Add the Model Viewer plugin for Flutter

public/data/glTF-projects-data.json
This is adding F3D to the list. F3D is a fast and minimalist 3D viewer supporting glTF thanks to VTK.
=> Adding F3D, a fast and minimalist 3D viewer.

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/80 
We might want to keep this open for a few days: There is not yet much information available. The plugin does not yet seem to be on the marketplace, and *when* it is available, we could add the marketplace link in the description.
=> Add animech Unreal4Web

public/data/glTF-projects-data.json
Added the change from https://github.com/KhronosGroup/glTF-Project-Explorer/pull/82 here in a branch, pragmatically fixing the merge conflict...
=> Added Emersya Platform

public/data/glTF-projects-data.json
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/99 : "New Project: Poimandres Market"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/100 : "New Project: Nomad Sculpt"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/101 : "New Project: 3D Comic toolkit for Blender"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/102 : "New Project: ReadyPlayerMe"
- Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/103 : "New Project: V-Ray glTF viewer"
=> Added projects from issues, 2021-05-27

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/105
It's only a single project this time, and not sooo much information about it, but in doubt, the entry can be extended later.
<sub>I hesitated a bit... they don't even have that "Systémes" vs. "Systèmes" thing consistent on their own website, so I took the "è" from Wikipedia 😬 ...</sub>
=> Added projects from issues, 2021-06-29

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/107 
The `description` and `output` have been updated based on the information from the issue discussion.
=> Update information about Godot

public/data/glTF-projects-data.json
Update glTF-projects-data.json: add smapshot project.
=> Update glTF-projects-data.json: add smapshot

public/data/glTF-projects-data.json
=> Added Pixi3D

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/147
=> Add GLTF-tool

public/data/glTF-projects-data.json
Fixes https://github.com/KhronosGroup/glTF-Project-Explorer/issues/149
=> Add guc to projects data

public/data/glTF-projects-data.json
A few new entries have been added, based on the projects from the glTF ecosystem diagram.
=> Update projects data

public/data/glTF-projects-data.json
The link was wrong due to a copy&paste error
=> Fix pygltflib link

public/data/glTF-projects-data.json
Adds Okino PolyTrans entry to the glTF-projects-data.json
=> Add Okino PolyTrans to glTF-projects-data.json

public/data/glTF-projects-data.json
Free community driven public CDN for 3d models/other assets.
Will be releasing a 3d scene editor that lets you import images/models and export as glb scene, even supporting adding/editing new animations (05/27/2023).
Thank you.
=> Added Filer to glTF-projects-data.json

public/data/glTF-projects-data.json
=> Added Needle Engine

public/data/glTF-projects-data.json
Quick update of NVIDIA's Omniverse USD Composer import and export capabilities. Based on [the documentation](https://docs.omniverse.nvidia.com/composer/latest/common/formats.html) and the application itself.
=> Update Omniverse import/export

README.md
Updated the instructions and the links. Also realized I forgot to update the build badge for actions so I did that as well.
=> Updated README.md with the info for the wordpress version of the site
